/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/Hangar.glb -o src/components/HangarNew.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function HangarNew(props) {
  const { nodes, materials } = useGLTF('/models/Hangar.glb')
  return (
    <group {...props} dispose={null} scale={50} position={[0, 34,200]}>
      <mesh geometry={nodes.Mesh_1.geometry} material={materials.Base} position={[0.008, -0.282, -4.887]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Mesh_1_1.geometry} material={materials.Details_Cevre} position={[0.008, -0.282, -4.887]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Mesh_1_2.geometry} material={materials.SVGMat} position={[0.008, -0.282, -4.887]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/Hangar.glb')
