/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/Hangar.glb -o src/components/Hangar.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Hangar(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Hangar.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}  scale={20}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="24cbae276e214082b4b2a44262456a44fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="Cylinder001" position={[0, 12.325, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cylinder001_Base_0" geometry={nodes.Cylinder001_Base_0.geometry} material={materials.Base} />
              </group>
              <group name="Plane" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Plane_Details_Cevre_0" geometry={nodes.Plane_Details_Cevre_0.geometry} material={materials.Details_Cevre} />
                <mesh name="Plane_Details_Cevre_0001" geometry={nodes.Plane_Details_Cevre_0001.geometry} material={materials.Details_Cevre} />
                <mesh name="Plane_Details_Cevre_0002" geometry={nodes.Plane_Details_Cevre_0002.geometry} material={materials.Details_Cevre} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model001" position={[0.015, 0, -9.769]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
          <group name="24cbae276e214082b4b2a44262456a44fbx001" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode001">
              <group name="Cylinder002" position={[0, 12.325, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Cylinder001_Base_0001" geometry={nodes.Cylinder001_Base_0001.geometry} material={materials.Base} />
              </group>
              <group name="Plane001" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Plane_Details_Cevre_0003" geometry={nodes.Plane_Details_Cevre_0003.geometry} material={materials.Details_Cevre} />
                <mesh name="Plane_Details_Cevre_0004" geometry={nodes.Plane_Details_Cevre_0004.geometry} material={materials.Details_Cevre} />
                <mesh name="Plane_Details_Cevre_0005" geometry={nodes.Plane_Details_Cevre_0005.geometry} material={materials.Details_Cevre} />
              </group>
            </group>
          </group>
        </group>
        <mesh name="Curve012" geometry={nodes.Curve012.geometry} material={materials.SVGMat} position={[0.015, -0.119, -0.137]} rotation={[Math.PI / 2, 0, Math.PI]} scale={27.211} />
        <mesh name="Curve001" geometry={nodes.Curve001.geometry} material={materials.SVGMat} position={[0.015, -0.119, -9.859]} rotation={[Math.PI / 2, 0, Math.PI]} scale={27.211} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Hangar.glb')
