/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\models\LoomCity.glb -o .\src\components\loomCity.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LoomCity(props) {
  const { nodes, materials } = useGLTF('/models/LoomCity.glb')
  return (
    <group {...props} dispose={null}  >
      <mesh geometry={nodes.città.geometry} material={materials.multi} />
      <mesh geometry={nodes.Plane.geometry} material={materials.multi} />
      <mesh geometry={nodes.Plane030.geometry} material={materials.multi} />
      <mesh geometry={nodes.Plane034.geometry} material={materials.multi} />
      <mesh geometry={nodes.Plane036.geometry} material={materials.multi} />
      <mesh geometry={nodes.Plane037.geometry} material={materials.multi} />
      <mesh geometry={nodes.Plane038.geometry} material={materials.multi} />
      <mesh geometry={nodes.Nuvole_medie.geometry} material={materials.multicolor} />
      <mesh geometry={nodes.Nuvole_grande001.geometry} material={materials.multicolor} />
      <mesh geometry={nodes.nuvole_piccole001.geometry} material={materials.multi} />
      <mesh geometry={nodes.Nuvole_grande002.geometry} material={materials.multicolor} />
      <mesh geometry={nodes.Nuvole_grande003.geometry} material={materials.multicolor} />
      <mesh geometry={nodes.nuvole_piccole003.geometry} material={materials.multi} />
      <mesh geometry={nodes.Nuvole_medie004.geometry} material={materials.multicolor} />
      <mesh geometry={nodes.Nuvole_grande004.geometry} material={materials.multicolor} />
      <mesh geometry={nodes.Nuvole_grande005.geometry} material={materials.multicolor} />
      <mesh geometry={nodes.Icosphere020.geometry} material={materials.sassy} />
      <mesh geometry={nodes.superpino008.geometry} material={materials.multi} />
      <mesh geometry={nodes.alberello001.geometry} material={materials.multi} />
      <mesh geometry={nodes.alberello002.geometry} material={materials.multi} />
      <mesh geometry={nodes.alberello003.geometry} material={materials.multi} />
      <mesh geometry={nodes.alberello004.geometry} material={materials.multi} />
      <mesh geometry={nodes.alberello005.geometry} material={materials.multi} />
      <mesh geometry={nodes.alberello006.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino002.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino003.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino004.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino005.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino006.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino_aperto.geometry} material={materials.multi} />
      <mesh geometry={nodes.pino001.geometry} material={materials.multi} />
      <mesh geometry={nodes.pino002.geometry} material={materials.multi} />
      <mesh geometry={nodes.pino003.geometry} material={materials.multi} />
      <mesh geometry={nodes.pino004.geometry} material={materials.multi} />
      <mesh geometry={nodes.superpino.geometry} material={materials.multi} />
      <mesh geometry={nodes.superpino002.geometry} material={materials.multi} />
      <mesh geometry={nodes.superpino003.geometry} material={materials.multi} />
      <mesh geometry={nodes.superpino004.geometry} material={materials.multi} />
      <mesh geometry={nodes.superpino005.geometry} material={materials.multi} />
      <mesh geometry={nodes.superpino006.geometry} material={materials.multi} />
      <mesh geometry={nodes.TAVOLO.geometry} material={materials.multi} />
      <mesh geometry={nodes.TAVOLO001.geometry} material={materials.multi} />
      <mesh geometry={nodes.TAVOLO002.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante002.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante003.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante004.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante005.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante006.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante007.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante008.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina001.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina002.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina003.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina004.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina005.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina006.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina007.geometry} material={materials.multi} />
      <mesh geometry={nodes.SEMI_PANCHINA.geometry} material={materials.multi} />
      <mesh geometry={nodes.SEMI_PANCHINA001.geometry} material={materials.multi} />
      <mesh geometry={nodes.SEMI_PANCHINA002.geometry} material={materials.multi} />
      <mesh geometry={nodes.SEMI_PANCHINA003.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso001.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso002.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso003.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso004.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso005.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso006.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso007.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso008.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso009.geometry} material={materials.multi} />
      <mesh geometry={nodes.VASO_ALTO.geometry} material={materials.multi} />
      <mesh geometry={nodes.VASO_ALTO_1.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino_aperto001.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino_aperto002.geometry} material={materials.multi} />
      <mesh geometry={nodes.superpino001.geometry} material={materials.multi} />
      <mesh geometry={nodes.pino005.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino001.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino007.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino_aperto003.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino_aperto004.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino_aperto005.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino_aperto006.geometry} material={materials.multi} />
      <mesh geometry={nodes.alberello007.geometry} material={materials.multi} />
      <mesh geometry={nodes.pino006.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso010.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso011.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso012.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso013.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso014.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso015.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso016.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso017.geometry} material={materials.multi} />
      <mesh geometry={nodes.VASO_ALTO_1001.geometry} material={materials.multi} />
      <mesh geometry={nodes.pino007.geometry} material={materials.multi} />
      <mesh geometry={nodes.pino008.geometry} material={materials.multi} />
      <mesh geometry={nodes.pino009.geometry} material={materials.multi} />
      <mesh geometry={nodes.pino010.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina008.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina009.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina010.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina011.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina012.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina013.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina014.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina015.geometry} material={materials.multi} />
      <mesh geometry={nodes.TAVOLO003.geometry} material={materials.multi} />
      <mesh geometry={nodes.SEMI_PANCHINA004.geometry} material={materials.multi} />
      <mesh geometry={nodes.SEMI_PANCHINA005.geometry} material={materials.multi} />
      <mesh geometry={nodes.TAVOLO004.geometry} material={materials.multi} />
      <mesh geometry={nodes.SEMI_PANCHINA006.geometry} material={materials.multi} />
      <mesh geometry={nodes.SEMI_PANCHINA007.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina016.geometry} material={materials.multi} />
      <mesh geometry={nodes.panchina017.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino_aperto007.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino_aperto008.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino_aperto009.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante001.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante009.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante010.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante011.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante012.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante013.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante014.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante015.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante016.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante017.geometry} material={materials.multi} />
      <mesh geometry={nodes.superpino007.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso018.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso019.geometry} material={materials.multi} />
      <mesh geometry={nodes.TAVOLO005.geometry} material={materials.multi} />
      <mesh geometry={nodes.SEMI_PANCHINA008.geometry} material={materials.multi} />
      <mesh geometry={nodes.SEMI_PANCHINA009.geometry} material={materials.multi} />
      <mesh geometry={nodes.alberello008.geometry} material={materials.multi} />
      <mesh geometry={nodes.alberello009.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso020.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso021.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso022.geometry} material={materials.multi} />
      <mesh geometry={nodes.vaso023.geometry} material={materials.multi} />
      <mesh geometry={nodes.lampione045.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante018.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante019.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante020.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante021.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante022.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante023.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante024.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante025.geometry} material={materials.multi} />
      <mesh geometry={nodes.idrante026.geometry} material={materials.multi} />
      <mesh geometry={nodes.cestino_aperto010.geometry} material={materials.multi} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane008.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane010.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane009.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane011.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane012.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane013.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane014.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane015.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane016.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane017.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane018.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane019.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane020.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane021.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane022.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane023.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane024.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane025.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane026.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane027.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane028.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.SEMAFORO001.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.SEMAFORO002.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.SEMAFORO003.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.SEMAFORO004.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.DIVIETO_2001.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.cono_001.geometry} material={materials.multi} />
      <mesh geometry={nodes.cono_002.geometry} material={materials.multi} />
      <mesh geometry={nodes.DIVIETO_2002.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.DIVIETO_DI001.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.GIALLO001.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.GIALLO002.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.FRECCIA001.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Plane033.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane029.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane031.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane032.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane035.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.PARCHEGGIO002.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.PARCHEGGIO003.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.PARCHEGGIO001.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.PARCHEGGIO004.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Plane039.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane040.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane041.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane042.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane043.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane044.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane045.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Plane047.geometry} material={materials['strisce pedo']} />
      <mesh geometry={nodes.Text.geometry} material={materials['trasp.001']} position={[-45.817, 89.425, -171.539]} rotation={[Math.PI / 2, 0, 0]} scale={25.385} />
      <mesh geometry={nodes.Text001.geometry} material={materials['trasp.002']} position={[37.234, 74.707, -165.358]} rotation={[Math.PI / 2, 0, 0]} scale={15.801} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube016_1.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cube040.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube040_1.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cube042.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube042_1.geometry} material={materials['biannco.001']} />
      <mesh geometry={nodes.Cube042_2.geometry} material={materials['arieggiacoso.001']} />
      <mesh geometry={nodes.Cube042_3.geometry} material={materials['soso.001']} />
      <mesh geometry={nodes.Cube042_4.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cube045.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube045_1.geometry} material={materials['trasp.002']} />
      <mesh geometry={nodes.Cube045_2.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube001_2.geometry} material={materials['vetri non trasp']} />
      <mesh geometry={nodes.Cube026.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube026_1.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cube066.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube066_1.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cube068.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube068_1.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cube069.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube069_1.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cube075.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube075_1.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cube076.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube076_1.geometry} material={materials['vetri non trasp']} />
      <mesh geometry={nodes.Cube078.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube078_1.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cube119.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube119_1.geometry} material={materials['trasp.002']} />
      <mesh geometry={nodes.Cube119_2.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cylinder051.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder051_1.geometry} material={materials['trasp.002']} />
      <mesh geometry={nodes.Cylinder041.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder041_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder042.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder042_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder043.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder043_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder044.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder044_1.geometry} material={materials['trasp.002']} />
      <mesh geometry={nodes.Cylinder045.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder045_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder046.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder046_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder047.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder047_1.geometry} material={materials['trasp.002']} />
      <mesh geometry={nodes.Cylinder048.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder048_1.geometry} material={materials['trasp.002']} />
      <mesh geometry={nodes.Cylinder049.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder049_1.geometry} material={materials['trasp.002']} />
      <mesh geometry={nodes.Cylinder050.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder050_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder052.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder052_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder053.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder053_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder054.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder054_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder055.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder055_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder056.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder056_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder057.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder057_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder058.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder058_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder059.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder059_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder060.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder060_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube048.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube048_1.geometry} material={materials['specchio.001']} />
      <mesh geometry={nodes.Cube048_2.geometry} material={materials['nero.003']} />
      <mesh geometry={nodes.Cube049.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube049_1.geometry} material={materials['specchio.001']} />
      <mesh geometry={nodes.Cube049_2.geometry} material={materials['nero.003']} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder_1.geometry} material={materials['biannco.001']} />
      <mesh geometry={nodes.Cylinder_2.geometry} material={materials.acqua} />
      <mesh geometry={nodes.Cube064.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube064_1.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cube065.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube065_1.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cube070.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube070_1.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cube077.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube077_1.geometry} material={materials['biannco.001']} />
      <mesh geometry={nodes.Cube077_2.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cube089.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube089_1.geometry} material={materials['specchio.001']} />
      <mesh geometry={nodes.Cube089_2.geometry} material={materials['nero.003']} />
      <mesh geometry={nodes.Cylinder079.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder079_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder080.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder080_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder081.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder081_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder082.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder082_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder083.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder083_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder084.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder084_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder085.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder085_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder086.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder086_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder087.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder087_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder088.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder088_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder089.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder089_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder090.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder090_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder091.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder091_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder092.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder092_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder093.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder093_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube122.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube122_1.geometry} material={materials['nero.003']} />
      <mesh geometry={nodes.Cube058.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube058_1.geometry} material={materials['trasp.001']} />
      <mesh geometry={nodes.Cylinder039.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder039_1.geometry} material={materials['trasp.002']} />
      <mesh geometry={nodes.Cylinder105.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder105_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder038.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder038_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder070.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder070_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder106.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder106_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder107.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder107_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder108.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder108_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder109.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder109_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder110.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder110_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder112.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder112_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder113.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder113_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder114.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder114_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder115.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder115_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder116.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder116_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cylinder117.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cylinder117_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube021.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube021_1.geometry} material={materials['vetri bus']} />
      <mesh geometry={nodes.Cube022.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube022_1.geometry} material={materials['specchio.001']} />
      <mesh geometry={nodes.Cube022_2.geometry} material={materials.VETRO} />
      <mesh geometry={nodes.Cube023.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube023_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube023_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube024.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube024_1.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube043.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube043_1.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube046.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube046_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube046_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube047.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube047_1.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube052.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube052_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube052_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube053.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube053_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube053_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube087.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube087_1.geometry} material={materials['specchio.001']} />
      <mesh geometry={nodes.Cube087_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube088.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube088_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube088_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube090.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube090_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube090_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube091.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube091_1.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube092.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube092_1.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube093.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube093_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube093_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube094.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube094_1.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube095.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube095_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube095_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube096.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube096_1.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube097.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube097_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube097_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube098.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube098_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube098_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube118.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube118_1.geometry} material={materials['vetri bus']} />
      <mesh geometry={nodes.Cube120.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube120_1.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube121.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube121_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube121_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube123.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube123_1.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube124.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube124_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube124_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube125.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube125_1.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube126.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube126_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube126_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube057.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube057_1.geometry} material={materials.fari} />
      <mesh geometry={nodes.Cube057_2.geometry} material={materials.vetro} />
      <mesh geometry={nodes.Cube129.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube129_1.geometry} material={materials['trasp.002']} />
      <mesh geometry={nodes.Cube129_2.geometry} material={materials['specchio.001']} />
      <mesh geometry={nodes.Cube132.geometry} material={materials.multi} />
      <mesh geometry={nodes.Cube132_1.geometry} material={materials['trasp.001']} />
    </group>
  )
}

useGLTF.preload('/models/LoomCity.glb')
